name: PocketDockConsole
main: PocketDockConsole\Main
version: 0.0.1
api: [1.0.0]

load: POSTWORLD
author: humerusj
description: A web console that uses WebSockets
website: https://github.com/Humerus/PocketDockConsole
commands:
permissions:
